author:
  name: Dinh-Tuyen Le
  email: tuyenld@circuitlover.com
  github: tuyenld
  linkedin: ledinhtuyen
  twitter: tuyen_ld
collections:
  newsletters:
    output: true
defaults:
  -
    scope:
      path: "_newsletters/**"
    values:
      sitemap: false
      image: /images/author.png
exclude:
  - yarn.lock
  - package-lock.json
  - README.md
  - postcss.config.js
  - purgecss.config.js
  - netlify.toml
  - bin
  - .gitignore
  - resources
  - node_modules
include:
  - .htaccess
  - _newsletters
markdown: kramdown
permalink: /:title
plugins:
#  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-postcss
  - jekyll-purgecss
url: https://circuitlover.com

# jekyll-seo-tag configuration
title: circuitlover.com
tagline: "IoT systems."
description: "A blog from Dinh-Tuyen Le."
logo: images/avatar-circle.png
twitter:
  username: tuyen_ld
  card: summary_large_image
social:
  name: Dinh-Tuyen Le
  links:
    - https://twitter.com/tuyen_ld
    - https://www.linkedin.com/in/ledinhtuyen
    - https://github.com/tuyenld


# tuyenld added
cloudinaryurl : "https://res.cloudinary.com/crushcoding/image/upload/q_auto,f_auto/"
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "post"

# Set which comment system to use
comments:
  # 'disqus' or 'utterances' are available
  provider:            giscus

analytics:
  provider: ""

# You must install utterances github app before use.(https://github.com/apps/utterances)
# Make sure all variables are set properly. Check below link for detail.
# https://utteranc.es/
utterances:
  repo:                "LazyRen/LazyRen.github.io"
  issue-term:          "pathname"
  label:               "Comments"
  theme:               "dark-blue"

# You must install giscus github app before use.(https://github.com/apps/giscus)
# Make sure all variables are set properly. Check below link for detail.
# https://giscus.vercel.app/
giscus:
  repo:                "tuyenld/circuitlover"
  repo-id:             "R_kgDOGon9FA"
  category:            "Announcements"
  category-id:         "DIC_kwDOGon9FM4CA0Wc"
  mapping:             "pathname"
  reaction-enabled:    "1"
  theme:               "light"
  crossorigin:         "anonymous"

repository : "tuyenld/circuitlover"
# deployment
host: 0.0.0.0
# port: 4000
